name: tests

on:
 push:

jobs:
 test:
  runs-on: ubuntu-latest

  steps:
   - name: fetch code
     uses: actions/checkout@v4

   - name: install Valgrind
     run: sudo apt-get update && sudo apt-get install -y valgrind

   - name: check for tools
     run: |
      clang -v
      make -v
      valgrind --version

   - name: compile
     run: make

   - name: run non interactive tests
     run: |
      CASES_PATH="tests_cases"
      ./seddari unknown   2> "$CASES_PATH/unknown/compare.out"        || true
      ./seddari -a        2> "$CASES_PATH/address-short/compare.out"  || true
      ./seddari --address 2> "$CASES_PATH/address-long/compare.out"   || true
      ./seddari -p        2> "$CASES_PATH/port-short/compare.out"     || true
      ./seddari --port    2> "$CASES_PATH/port-long/compare.out"      || true
      ./seddari -h        >  "$CASES_PATH/help-short/compare.out"
      ./seddari --help    >  "$CASES_PATH/help-long/compare.out"
      for case_dir in "$CASES_PATH"/*; do
        echo "Testing $case_dir"
        diff -u "$case_dir/expected.out" "$case_dir/compare.out"
      done

   - name: run tests
     run: |
      VALGRIND_OPTIONS="--leak-check=full --show-leak-kinds=all --track-fds=yes --errors-for-leak-kinds=all --error-exitcode=1"
      run_valgrind_test() {
       expected_status="$1"
       shift
       valgrind $VALGRIND_OPTIONS "$@"
       actual_status=$?
       if [ "$actual_status" -ne "$expected_status" ]; then
         echo "Expected exit code $expected_status, got $actual_status"
         return 1
       fi
       }
      run_valgrind_test 1 ./seddari unknown
      run_valgrind_test 0 ./seddari -h
      run_valgrind_test 0 ./seddari --help
      run_valgrind_test 1 ./seddari -a        
      run_valgrind_test 1 ./seddari --address 
      run_valgrind_test 1 ./seddari -p        
      run_valgrind_test 1 ./seddari --port    
